name: LACES
favicon: null
layout_spectrum: 0.60085
typography_spectrum: 0.06511
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1d447f'
    - '#5099cb'
    - '#4e678d'
    - '#1f1b1a'
  brandStrength: 0.75
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
