name: LACES
favicon: null
layout_spectrum: 1
typography_spectrum: 0.63664
title: LACES - The London Anti-Crime Education Scheme
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1d447f'
    - '#cddae9'
    - '#949494'
    - '#516588'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
