name: LACES
favicon: null
layout_spectrum: 0.76344
typography_spectrum: 0.07099
title: LACES - The London Anti-Crime Education Scheme
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1d447f'
    - '#cddae9'
    - '#949494'
    - '#516588'
  brandStrength: 0.75
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
