name: LACES
favicon: null
layout_spectrum: 0.6811594013124704
typography_spectrum: 0.7134876379277557
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7144380421377718
  lightness: 0.010542397852987051
  saturation: 0.5876739292871207
  rhythmicContrast: 0.3459633640013635
purpose: []
